#%RAML 1.0
title: mail-sys-api
version: v1
description: This API can send Email to the Team Leaders, and get emails by ID.

types: 
  sendMail: !include /Datatype/sendMail-DataType.raml

/mails:
  displayName: sendMail
  post:
    description: This path will send Mail for Team Leaders.
    body:
      application/json:
        example:
    responses:
      200:
        body:
          application/json:
            example: !include /Example/sendMail-example.raml

  /{ID}:
    displayName: getMail
    get:
      description: This path will get Mail by ID.
      responses:
        200:
          body:
            application/json:
              example:
                message: "Get the Mails Successfully!"