api:
  id: "19291926"
 
smtp:
  host: "smtp.gmail.com"
  port: "587"
  user: "joaodev8@gmail.com"
  pass: "gelt ycgk fufi wvru"
  
imap:
  host: "imap.gmail.com"
  port: "993"
  user: "joaomulesoft@gmail.com"
  pass: "gelt ycgk fufi wvru"
 
db:
  url: "jdbc:postgresql://database-1.c9r1lsfx7e56.eu-central-1.rds.amazonaws.com:5432/incidents"
  driver: "org.postgresql.Driver"
  user: "postgres"
  pass: "Yc&8q1VNUFs1"